const mongoose = require('mongoose');

const STUDENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DEBARRED: 'DEBARRED',
};

const studentSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    admissionNumber: { type: String, required: true, unique: true },
    mobileNumber: { type: String, required: true },
    email: { type: String, required: true, lowercase: true },
    semester: { type: String, required: true },
    section: { type: String, required: true },
    department: { type: String, required: true },
    status: {
      type: String,
      enum: Object.values(STUDENT_STATUS),
      default: STUDENT_STATUS.ACTIVE,
    },
    qrSecret: {
      type: String,
      required: true,
      unique: true,
    },
    // Optional fields populated when QR is generated by the Flask service
    qrPayload: { type: String },
    qrImageUrl: { type: String },
  },
  { timestamps: true }
);

module.exports = {
  Student: mongoose.model('Student', studentSchema),
  STUDENT_STATUS,
};
